import {useEffect,useMemo,useState} from 'react';
import {Routes,Route,Link,useNavigate} from 'react-router-dom';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,User} from 'firebase/auth';
import {collection,getDocs,orderBy,query} from 'firebase/firestore';
import {auth,configured,db} from './firebase';import {isAdmin,save} from './data';import type {Match,Player,Season,PlayerStat} from './types';
import {Shield,Users,Trophy,CalendarDays,LogIn,LogOut,Plus,BarChart3} from 'lucide-react';
const emptyStats:PlayerStat[]=[];
function usePublicData(){const [players,setPlayers]=useState<Player[]>([]),[seasons,setSeasons]=useState<Season[]>([]),[matches,setMatches]=useState<Match[]>([]),[stats,setStats]=useState<PlayerStat[]>(emptyStats),[loading,setLoading]=useState(true);useEffect(()=>{if(!configured){setLoading(false);return;} Promise.all(['players','seasons','matches','playerCareerStats'].map(async n=>{const s=await getDocs(query(collection(db,n),orderBy(n==='matches'?'date':n==='seasons'?'label':n==='playerCareerStats'?'goals':'displayName',n==='matches'||n==='playerCareerStats'?'desc':'asc')));return s.docs.map(d=>({id:d.id,...d.data()}));})).then(([p,s,m,st])=>{setPlayers((p as Player[]).filter(x=>x.status==='published'));setSeasons((s as Season[]).filter(x=>x.status==='published'));setMatches((m as Match[]).filter(x=>x.status==='published'));setStats((st as PlayerStat[]));}).finally(()=>setLoading(false));},[]);return{players,seasons,matches,stats,loading};}
function Shell({children,user,admin}:{children:React.ReactNode,user:User|null,admin:boolean}){return <><header><Link className="brand" to="/"><img src="/logo-bnc.png"/><span><b>A.C. BNC</b><small>Archivio Prima Squadra</small></span></Link><nav><Link to="/stagioni">Stagioni</Link><Link to="/giocatori">Giocatori</Link><Link to="/partite">Partite</Link><Link to="/record">Record</Link>{admin&&<Link to="/admin">Gestione</Link>}{user?<button className="linkbtn" onClick={()=>signOut(auth)}><LogOut size={17}/> Esci</button>:<Link to="/login"><LogIn size={17}/> Accedi</Link>}</nav></header><main>{children}</main><footer>A.C. BNC · Archivio storico della Prima Squadra</footer></>}
function Home({d}:{d:ReturnType<typeof usePublicData>}){const totals=useMemo(()=>d.matches.reduce((a,m)=>({p:a.p+1,v:a.v+(m.officialGoalsFor>m.officialGoalsAgainst?1:0),gf:a.gf+m.officialGoalsFor,gs:a.gs+m.officialGoalsAgainst}),{p:0,v:0,gf:0,gs:0}),[d.matches]);return <><section className="hero"><div><span className="eyebrow">DAL 2020 A OGGI</span><h1>La storia della Prima Squadra,<br/>raccontata dai dati.</h1><p>Risultati, rose, protagonisti, record e albo d'oro in un archivio unico e costantemente aggiornato.</p><Link className="cta" to="/stagioni">Esplora l'archivio</Link></div><img src="/logo-bnc.png"/></section><section className="metricgrid"><Metric icon={<CalendarDays/>} n={totals.p} t="Partite ufficiali"/><Metric icon={<Trophy/>} n={totals.v} t="Vittorie"/><Metric icon={<BarChart3/>} n={totals.gf} t="Gol fatti"/><Metric icon={<Shield/>} n={Math.max(0,totals.gf-totals.gs)} t="Differenza reti"/></section><section><Title>Ultime partite</Title><MatchList items={d.matches.slice(0,6)}/></section></>}
function Metric({icon,n,t}:{icon:React.ReactNode,n:number,t:string}){return <article className="metric"><i>{icon}</i><strong>{n}</strong><span>{t}</span></article>}
function Title({children}:{children:React.ReactNode}){return <h2 className="sectiontitle">{children}</h2>}
function MatchList({items}:{items:Match[]}){return <div className="list">{items.map(m=><article className="match" key={m.id}><div><b>{m.competition}</b><small>{m.date} · {m.venue}</small></div><strong>A.C. BNC <em>{m.officialGoalsFor} - {m.officialGoalsAgainst}</em> {m.opponent}</strong></article>)}{!items.length&&<Empty/>}</div>}
function Seasons({d}:{d:ReturnType<typeof usePublicData>}){return <><Title>Stagioni</Title><div className="cards">{d.seasons.map(s=><article className="card" key={s.id}><span className="eyebrow">{s.category}</span><h3>{s.label}</h3><p>Allenatore: {s.coach||'Da completare'}</p><p>{s.position?`${s.position}° posto · `:''}{s.points??'–'} punti</p></article>)}{!d.seasons.length&&<Empty/>}</div></>}
function Players({d}:{d:ReturnType<typeof usePublicData>}){return <><Title>Classifiche individuali</Title><div className="tablewrap"><table><thead><tr><th>#</th><th>Giocatore</th><th>Pres.</th><th>Gol</th><th>Assist</th><th>Gialli</th><th>Rossi</th></tr></thead><tbody>{d.stats.sort((a,b)=>b.goals-a.goals).map((s,i)=><tr key={s.playerId}><td>{i+1}</td><td><b>{s.displayName}</b></td><td>{s.appearances}</td><td>{s.goals}</td><td>{s.assists}</td><td>{s.yellows}</td><td>{s.reds}</td></tr>)}</tbody></table>{!d.stats.length&&<Empty/>}</div></>}
function Matches({d}:{d:ReturnType<typeof usePublicData>}){return <><Title>Archivio partite</Title><MatchList items={d.matches}/></>}
function Records({d}:{d:ReturnType<typeof usePublicData>}){const best=[...d.seasons].sort((a,b)=>(b.points||0)-(a.points||0))[0];const top=[...d.stats].sort((a,b)=>b.goals-a.goals)[0];return <><Title>Record e albo d'oro</Title><div className="cards"><article className="card gold"><h3>Maggior numero di punti</h3><strong>{best?.points??'–'}</strong><p>{best?.label??'Dati in importazione'}</p></article><article className="card gold"><h3>Marcatore all time</h3><strong>{top?.goals??'–'}</strong><p>{top?.displayName??'Dati in importazione'}</p></article><article className="card"><h3>Coppa Verona</h3><strong>2</strong><p>2023/24 · 2025/26</p></article></div></>}
function Login(){const nav=useNavigate();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');async function go(e:React.FormEvent){e.preventDefault();try{await signInWithEmailAndPassword(auth,email,password);nav('/admin');}catch{setErr('Accesso non riuscito. Controlla email e password.');}}return <form className="panel login" onSubmit={go}><Title>Accesso amministratori</Title><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{err&&<p className="error">{err}</p>}<button className="cta">Accedi</button></form>}
function Admin({ok}:{ok:boolean}){const [tab,setTab]=useState<'players'|'seasons'|'matches'>('players');if(!ok)return <div className="panel"><Title>Accesso non autorizzato</Title><p>L'account è autenticato ma non è presente nella raccolta <code>admins</code>.</p></div>;return <><div className="adminhead"><Title>Gestione archivio</Title><div>{(['players','seasons','matches'] as const).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='players'?'Giocatori':x==='seasons'?'Stagioni':'Partite'}</button>)}</div></div>{tab==='players'&&<PlayerForm/>}{tab==='seasons'&&<SeasonForm/>}{tab==='matches'&&<MatchForm/>}</>}
function PlayerForm(){const [name,setName]=useState(''),[role,setRole]=useState('');return <form className="panel" onSubmit={async e=>{e.preventDefault();await save('players',undefined,{displayName:name,role,active:true,status:'published'});setName('');setRole('');alert('Giocatore salvato');}}><h3><Plus/> Nuovo giocatore</h3><div className="formgrid"><label>Nome visualizzato<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Ruolo<select value={role} onChange={e=>setRole(e.target.value)} required><option value="">Seleziona</option><option>Portiere</option><option>Difensore</option><option>Centrocampista</option><option>Attaccante</option></select></label></div><button className="cta">Salva</button></form>}
function SeasonForm(){const [label,setLabel]=useState('2026/2027'),[category,setCategory]=useState('Terza Categoria'),[coach,setCoach]=useState('');return <form className="panel" onSubmit={async e=>{e.preventDefault();await save('seasons',undefined,{label,category,coach,status:'published'});alert('Stagione salvata');}}><h3><Plus/> Nuova stagione</h3><div className="formgrid"><label>Stagione<input value={label} onChange={e=>setLabel(e.target.value)} required/></label><label>Categoria<input value={category} onChange={e=>setCategory(e.target.value)} required/></label><label>Allenatore<input value={coach} onChange={e=>setCoach(e.target.value)}/></label></div><button className="cta">Salva</button></form>}
function MatchForm(){const [f,setF]=useState({seasonId:'2026/2027',date:'',competition:'Campionato',opponent:'',venue:'Casa',goalsFor:0,goalsAgainst:0});return <form className="panel" onSubmit={async e=>{e.preventDefault();await save('matches',undefined,{...f,officialGoalsFor:Number(f.goalsFor),officialGoalsAgainst:Number(f.goalsAgainst),goalsFor:Number(f.goalsFor),goalsAgainst:Number(f.goalsAgainst),status:'published'});alert('Partita salvata');}}><h3><Plus/> Nuova partita</h3><div className="formgrid">{[['seasonId','Stagione'],['date','Data'],['competition','Competizione'],['opponent','Avversario']].map(([k,l])=><label key={k}>{l}<input type={k==='date'?'date':'text'} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})} required/></label>)}<label>Campo<select value={f.venue} onChange={e=>setF({...f,venue:e.target.value})}><option>Casa</option><option>Trasferta</option></select></label><label>Gol BNC<input type="number" min="0" value={f.goalsFor} onChange={e=>setF({...f,goalsFor:Number(e.target.value)})}/></label><label>Gol avversario<input type="number" min="0" value={f.goalsAgainst} onChange={e=>setF({...f,goalsAgainst:Number(e.target.value)})}/></label></div><button className="cta">Salva e pubblica</button></form>}
function Empty(){return <div className="empty">I dati verranno visualizzati dopo l'importazione dello storico.</div>}
export default function App(){const d=usePublicData();const [user,setUser]=useState<User|null>(null),[admin,setAdmin]=useState(false);useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);setAdmin(u?await isAdmin(u.uid):false);}),[]);return <Shell user={user} admin={admin}>{!configured&&<div className="notice">Firebase non è ancora configurato. Compila il file <code>.env</code> seguendo il README.</div>}{d.loading?<div className="loader">Caricamento archivio…</div>:<Routes><Route path="/" element={<Home d={d}/>}/><Route path="/stagioni" element={<Seasons d={d}/>}/><Route path="/giocatori" element={<Players d={d}/>}/><Route path="/partite" element={<Matches d={d}/>}/><Route path="/record" element={<Records d={d}/>}/><Route path="/login" element={<Login/>}/><Route path="/admin" element={<Admin ok={admin}/>}/></Routes>}</Shell>}
