import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link, Route, Routes, useNavigate } from "react-router-dom";
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, type User } from "firebase/auth";
import { BarChart3, CalendarDays, LogIn, LogOut, Plus, Shield, Trophy, Users } from "lucide-react";
import { auth, configured } from "./firebase";
import { isAdmin, listAll, remove, save } from "./data";
import type { Coach, CompetitionType, Match, Opponent, Player, Season, SquadMember } from "./types";

interface PlayerSeasonStat {
  id: string;
  seasonId: string;
  playerId: string;
  displayName: string;
  appearances: number;
  goals: number;
  assists: number;
  status: string;
}
interface TrophyRecord { id:string; seasonId:string; name:string; result:string; date?:string; status:string; }
interface SeasonWithAggregates extends Season {
  aggregates?: { officialMatches:number; wins:number; draws:number; losses:number; goalsFor:number; goalsAgainst:number; goalDifference:number };
  league?: { position?:number; points?:number; wins?:number; draws?:number; losses?:number; goalsFor?:number; goalsAgainst?:number };
}
interface CareerStat { playerId:string; displayName:string; appearances:number; goals:number; assists:number; seasons:number; }
interface Data {
  players: Player[]; coaches: Coach[]; opponents: Opponent[]; seasons: SeasonWithAggregates[];
  squads: SquadMember[]; matches: Match[]; playerSeasonStats: PlayerSeasonStat[]; trophies: TrophyRecord[];
  loading:boolean; reload:()=>void;
}
const isOfficial=(m:Match)=>m.competitionType!=="friendly";
function useData():Data {
  const [refresh,setRefresh]=useState(0); const [loading,setLoading]=useState(true);
  const [data,setData]=useState<Omit<Data,"loading"|"reload">>({players:[],coaches:[],opponents:[],seasons:[],squads:[],matches:[],playerSeasonStats:[],trophies:[]});
  useEffect(()=>{ if(!configured){setLoading(false);return;} setLoading(true);
    Promise.all([
      listAll<Player>("players","displayName"), listAll<Coach>("coaches","displayName"), listAll<Opponent>("opponents","name"),
      listAll<SeasonWithAggregates>("seasons","label","desc"), listAll<SquadMember>("seasonSquads"), listAll<Match>("matches","date","desc"),
      listAll<PlayerSeasonStat>("playerSeasonStats"), listAll<TrophyRecord>("trophies","date","desc")
    ]).then(([players,coaches,opponents,seasons,squads,matches,playerSeasonStats,trophies])=>setData({players,coaches,opponents,seasons,squads,matches,playerSeasonStats,trophies})).catch(console.error).finally(()=>setLoading(false));
  },[refresh]); return {...data,loading,reload:()=>setRefresh(v=>v+1)};
}
function careerStats(d:Data):CareerStat[]{const map=new Map<string,CareerStat>(); for(const r of d.playerSeasonStats.filter(x=>x.status==="published")){const current=map.get(r.playerId)??{playerId:r.playerId,displayName:r.displayName,appearances:0,goals:0,assists:0,seasons:0};current.appearances+=r.appearances||0;current.goals+=r.goals||0;current.assists+=r.assists||0;current.seasons+=1;map.set(r.playerId,current);} return [...map.values()];}
function Shell({children,user,admin}:{children:ReactNode;user:User|null;admin:boolean}){return <><header><Link className="brand" to="/"><img src="/logo-bnc.png" alt="Logo A.C. BNC"/><span><b>A.C. BNC</b><small>Archivio Prima Squadra</small></span></Link><nav><Link to="/stagioni">Stagioni</Link><Link to="/giocatori">Giocatori</Link><Link to="/partite">Partite</Link><Link to="/record">Record</Link>{admin&&<Link to="/admin">Gestione</Link>}{user?<button className="linkbtn" onClick={()=>void signOut(auth)}><LogOut size={17}/> Esci</button>:<Link to="/login"><LogIn size={17}/> Accedi</Link>}</nav></header><main>{children}</main><footer>A.C. BNC · Archivio storico della Prima Squadra</footer></>}
const Title=({children}:{children:ReactNode})=><h2 className="sectiontitle">{children}</h2>;
const Empty=({text="Nessun dato disponibile."}:{text?:string})=><div className="empty">{text}</div>;
const Metric=({icon,value,label}:{icon:ReactNode;value:number|string;label:string})=><article className="metric"><i>{icon}</i><strong>{value}</strong><span>{label}</span></article>;
function Home({d}:{d:Data}){const actual=d.matches.filter(x=>x.status==="published"&&isOfficial(x));const aggregates=d.seasons.filter(x=>x.status==="published").reduce((a,s)=>({p:a.p+(s.aggregates?.officialMatches||0),v:a.v+(s.aggregates?.wins||0),gf:a.gf+(s.aggregates?.goalsFor||0),gs:a.gs+(s.aggregates?.goalsAgainst||0)}),{p:0,v:0,gf:0,gs:0});const live=actual.length?actual.reduce((a,m)=>({p:a.p+1,v:a.v+(m.goalsFor>m.goalsAgainst?1:0),gf:a.gf+m.goalsFor,gs:a.gs+m.goalsAgainst}),{p:0,v:0,gf:0,gs:0}):aggregates;return <><section className="hero"><div><span className="eyebrow">ARCHIVIO PRIMA SQUADRA</span><h1>La storia della Prima Squadra,<br/>raccontata dai dati.</h1><p>Campionato, coppe FIGC, playoff e playout. Le amichevoli sono escluse dalle statistiche.</p><Link className="cta" to="/stagioni">Esplora l'archivio</Link></div><img className="hero-logo" src="/logo-bnc.png" alt="Logo A.C. BNC"/></section><section className="metricgrid"><Metric icon={<CalendarDays/>} value={live.p} label="Partite ufficiali"/><Metric icon={<Trophy/>} value={live.v} label="Vittorie"/><Metric icon={<BarChart3/>} value={live.gf} label="Gol fatti"/><Metric icon={<Shield/>} value={live.gf-live.gs} label="Differenza reti"/></section><Title>Albo d'oro</Title>{d.trophies.length?<div className="cards">{d.trophies.filter(x=>x.status==="published").map(t=><article className="card gold" key={t.id}><span className="eyebrow">{d.seasons.find(s=>s.id===t.seasonId)?.label}</span><h3>{t.name}</h3><strong>{t.result}</strong><p>{t.date||""}</p></article>)}</div>:<Empty/>}{actual.length>0&&<><Title>Ultime partite</Title><MatchList matches={actual.slice(0,6)}/></>}</>}
function MatchList({matches}:{matches:Match[]}){return matches.length?<div className="list">{matches.map(m=><article className="match" key={m.id}><div><b>{m.competition}</b><small>{m.date} · {m.venue} · {m.seasonLabel}</small></div><strong>A.C. BNC <em>{m.goalsFor} - {m.goalsAgainst}</em> {m.opponent}</strong></article>)}</div>:<Empty text="Le singole partite saranno disponibili con la fase 2 dell'importazione."/>}
function Seasons({d}:{d:Data}){return <><Title>Stagioni</Title><div className="cards">{d.seasons.filter(s=>s.status==="published").map(s=><article className="card" key={s.id}><span className="eyebrow">{s.category}</span><h3>{s.label}</h3><p>{s.coach||""}</p><strong>{s.aggregates?.officialMatches??0}</strong><p>partite ufficiali · {s.aggregates?.wins??0} V · {s.aggregates?.draws??0} N · {s.aggregates?.losses??0} P</p><p>{s.aggregates?.goalsFor??0} GF · {s.aggregates?.goalsAgainst??0} GS · DR {s.aggregates?.goalDifference??0}</p>{s.league?.position&&<p><b>{s.league.position}° posto · {s.league.points??0} punti</b></p>}</article>)}</div></>}
function Players({d}:{d:Data}){const rows=careerStats(d).sort((a,b)=>b.appearances-a.appearances);return <><Title>Statistiche individuali all time</Title><div className="tablewrap"><table><thead><tr><th>#</th><th>Giocatore</th><th>Stagioni</th><th>Presenze</th><th>Gol</th><th>Assist</th><th>Gol + Assist</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.playerId}><td>{i+1}</td><td><b>{r.displayName}</b></td><td>{r.seasons}</td><td>{r.appearances}</td><td>{r.goals}</td><td>{r.assists}</td><td>{r.goals+r.assists}</td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></>}
function Matches({d}:{d:Data}){return <><Title>Archivio partite</Title><MatchList matches={d.matches.filter(x=>x.status==="published")}/></>}
function Records({d}:{d:Data}){const stats=careerStats(d),topGoals=[...stats].sort((a,b)=>b.goals-a.goals)[0],topApps=[...stats].sort((a,b)=>b.appearances-a.appearances)[0],topAssists=[...stats].sort((a,b)=>b.assists-a.assists)[0],best=[...d.seasons].sort((a,b)=>(b.league?.points||0)-(a.league?.points||0))[0];return <><Title>Record</Title><div className="cards"><article className="card gold"><h3>Marcatore all time</h3><strong>{topGoals?.goals??"–"}</strong><p>{topGoals?.displayName||"–"}</p></article><article className="card gold"><h3>Più presenze</h3><strong>{topApps?.appearances??"–"}</strong><p>{topApps?.displayName||"–"}</p></article><article className="card gold"><h3>Più assist</h3><strong>{topAssists?.assists??"–"}</strong><p>{topAssists?.displayName||"–"}</p></article><article className="card"><h3>Record punti</h3><strong>{best?.league?.points??"–"}</strong><p>{best?.label||"–"}</p></article></div></>}
function Login(){const nav=useNavigate(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await signInWithEmailAndPassword(auth,email,password);nav("/admin")}catch{setError("Accesso non riuscito")}}return <form className="panel login" onSubmit={submit}><Title>Accesso amministratori</Title><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button className="cta">Accedi</button></form>}
function Crud({collection,items,onAdd}:{collection:string;items:{id:string;label:string}[];onAdd:()=>void}){return <><button className="cta" onClick={onAdd}><Plus size={17}/> Nuovo</button><div className="list adminlist">{items.map(x=><article className="match" key={x.id}><b>{x.label}</b><button className="danger" onClick={async()=>{if(confirm("Eliminare?")){await remove(collection,x.id);location.reload()}}}>Elimina</button></article>)}</div></>}
function Admin({d,authorized}:{d:Data;authorized:boolean}){const [tab,setTab]=useState("summary"),[modal,setModal]=useState<string|null>(null);if(!authorized)return <div className="panel"><Title>Accesso non autorizzato</Title></div>;return <><Title>Gestione archivio</Title><div className="admintabs">{[["summary","Riepilogo"],["players","Giocatori"],["coaches","Allenatori"],["opponents","Avversari"],["seasons","Stagioni"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==="summary"&&<div className="metricgrid"><Metric icon={<Users/>} value={d.players.length} label="Giocatori"/><Metric icon={<CalendarDays/>} value={d.seasons.length} label="Stagioni"/><Metric icon={<Trophy/>} value={d.trophies.length} label="Trofei"/><Metric icon={<BarChart3/>} value={d.playerSeasonStats.length} label="Righe statistiche"/></div>}{tab==="players"&&<Crud collection="players" items={d.players.map(x=>({id:x.id,label:x.displayName}))} onAdd={()=>setModal("player")}/>} {tab==="coaches"&&<Crud collection="coaches" items={d.coaches.map(x=>({id:x.id,label:x.displayName}))} onAdd={()=>setModal("coach")}/>} {tab==="opponents"&&<Crud collection="opponents" items={d.opponents.map(x=>({id:x.id,label:x.name}))} onAdd={()=>setModal("opponent")}/>} {tab==="seasons"&&<Crud collection="seasons" items={d.seasons.map(x=>({id:x.id,label:`${x.label} · ${x.category}`}))} onAdd={()=>setModal("season")}/>} {modal&&<AddModal type={modal} close={()=>{setModal(null);d.reload()}}/>}</>}
function AddModal({type,close}:{type:string;close:()=>void}){const [a,setA]=useState(""),[b,setB]=useState("");async function submit(e:FormEvent){e.preventDefault();if(type==="player")await save("players",undefined,{displayName:a,role:b||"Da verificare",active:true,status:"published"});if(type==="coach")await save("coaches",undefined,{displayName:a,active:true,status:"published"});if(type==="opponent")await save("opponents",undefined,{name:a,active:true,status:"published"});if(type==="season")await save("seasons",undefined,{label:a,category:b,status:"published"});close()}return <div className="modal"><form className="panel" onSubmit={submit}><h3>Nuovo {type}</h3><label>Nome<input value={a} onChange={e=>setA(e.target.value)} required/></label>{(type==="player"||type==="season")&&<label>{type==="player"?"Ruolo":"Categoria"}<input value={b} onChange={e=>setB(e.target.value)} required/></label>}<button className="cta">Salva</button><button type="button" onClick={close}>Annulla</button></form></div>}
export default function App(){const d=useData(),[user,setUser]=useState<User|null>(null),[admin,setAdmin]=useState(false);useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);if(!u){setAdmin(false);return}void isAdmin(u.uid).then(setAdmin)}),[]);return <Shell user={user} admin={admin}>{d.loading?<div className="loader">Caricamento…</div>:<Routes><Route path="/" element={<Home d={d}/>}/><Route path="/stagioni" element={<Seasons d={d}/>}/><Route path="/giocatori" element={<Players d={d}/>}/><Route path="/partite" element={<Matches d={d}/>}/><Route path="/record" element={<Records d={d}/>}/><Route path="/login" element={<Login/>}/><Route path="/admin" element={<Admin d={d} authorized={admin}/>}/></Routes>}</Shell>}
